apiVersion: v1
kind: Service
metadata:
  name: zoom-info-scraper
  namespace: zoom-info
  labels:
    app: zoom-info-scraper
spec:
  selector:
    app: zoom-info-scraper
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
