apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml

helmCharts:
  - name: n8n
    releaseName: n8n
    repo: https://community-charts.github.io/helm-charts
    namespace: n8n
    version: 1.13.2
    valuesFile: values.yaml
