apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml

helmCharts:
  - name: n8n
    releaseName: n8n
    repo: 8gears.container-registry.com/library/n8n
    namespace: n8n
    version: 1.0.10
    valuesFile: values.yaml
