apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml

helmCharts:
  - name: n8n
    repo: https://8gears.github.io/n8n-helm-chart
    releaseName: n8n
    namespace: n8n
    version: 1.0.10
    valuesFile: values.yaml
