apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-database
  namespace: n8n
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    storageClass: longhorn
    size: 5Gi
  bootstrap:
    initdb:
      database: n8n-database
      owner: n8n
      secret:
        name: n8n-db-secret
