apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  selector:
    app.kubernetes.io/name: n8n
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
