log:
  level: warn

db:
  type: postgresdb

externalPostgresql:
  host: "n8n-db-rw.n8n.svc.cluster.local"
  username: "n8n"
  database: "n8n"

  existingSecret: "n8n-secrets"

main:
  count: 3 # Multiple replicas
  persistence:
    enabled: true
    type: dynamic
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: openebs-hostpath

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    cert-manager.io/common-name: workflow.isandeshsol.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: workflow.isandeshsol.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - workflow.isandeshsol.com
      secretName: n8n-tls

webhook:
  mode: queue
  url: "https://workflow.isandeshsol.com"
