apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: wordpress
    repo: https://charts.bitnami.com/bitnami
    releaseName: wordpress
    namespace: wordpress
    version: 25.0.1
    valuesFile: values.yaml
