mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: wordpress
    username: wpuser
    existingSecret: wp-database-secret
    # The secret must contain:
    #   - mariadb-password: user password
    #   - mariadb-root-password: root password
  primary:
    persistence:
      enabled: true
      storageClass: openebs-hostpath
      size: 10Gi

wordpressUsername: admin
wordpressEmail: admin@isandeshsol.com
wordpressFirstName: Sandesh
wordpressLastName: Solabannavar
existingSecret: wordpress-admin-secret

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: blog.isandeshsol.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    cert-manager.io/common-name: blog.isandeshsol.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls: true
  extraTls:
    - hosts:
        - blog.isandeshsol.com
      secretName: wordpress-tls

metrics:
  enabled: true

service:
  type: ClusterIP

wordpressBlog:
  debug: true

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 10Gi
