mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: wordpress
    username: wpuser
    existingSecret: wp-database-secret
    # The secret must contain:
    #   - mariadb-password: user password
    #   - mariadb-root-password: root password
  primary:
    persistence:
      enabled: true
      storageClass: openebs-hostpath
      size: 10Gi

wordpressUsername: admin
wordpressPassword: admin_password
wordpressEmail: admin@example.com
wordpressFirstName: Admin
wordpressLastName: User
wordpressBlogName: My WordPress Blog

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: wordpress.isandeshsol.com
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    cert-manager.io/common-name: wordpress.isandeshsol.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  extraTls:
    - hosts:
        - wordpress.isandeshsol.com
      secretName: wordpress-tls

persistence:
  enabled: true
  storageClass: openebs-hostpath
  accessMode: ReadWriteOnce
  size: 10Gi
