apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflow
  namespace: inflow
  labels:
    app: inflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflow
  template:
    metadata:
      labels:
        app: inflow
    spec:
      containers:
        - name: inflow
          image: ghcr.io/sandesh-solabannavar/in_flow:e2441ab # Fixed duplicate ghcr.io
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: inflow-app-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
