apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
helmCharts:
  - name: vault
    releaseName: vault
    repo: https://helm.releases.hashicorp.com
    namespace: vault
    version: 0.30.0
    valuesFile: values.yaml
