server:
  dev:
    enabled: true

  # service:
  #   enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-stg
      cert-manager.io/common-name: vault.isandeshsol.com
    hosts:
      - host: vault.isandeshsol.com
        paths:
          - path: /
    tls:
      - secretName: vault-tls
        hosts:
          - vault.isandeshsol.com

# Expose the Vault UI (optional)
ui:
  enabled: true
  serviceType: "ClusterIP"
