# Available parameters and their default values for the Vault chart.
global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true

server:
  # If true, or "-" with global.enabled true, Vault server will be installed.
  # See vault.mode in _helpers.tpl for implementation details.
  enabled: true

  # Configure the logging verbosity for the Vault server.
  # Supported log levels include: trace, debug, info, warn, error
  logLevel: "warn"

  # Configure the logging format for the Vault server.
  # Supported log formats include: standard, json
  logFormat: "json"

  # Ingress allows ingress services to be created to allow external access
  # from Kubernetes to access Vault pods.
  # If deployment is on OpenShift, the following block is ignored.
  # In order to expose the service, use the route section below
  ingress:
    enabled: true
    labels:
      {}
      # traffic: external
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-stg
      cert-manager.io/common-name: vault.isandeshsol.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

    # Optionally use ingressClassName instead of deprecated annotation.
    # See: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
    ingressClassName: "traefik"

    # As of Kubernetes 1.19, all Ingress Paths must have a pathType configured. The default value below should be sufficient in most cases.
    # See: https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types for other possible values.
    pathType: Prefix

    # When HA mode is enabled and K8s service registration is being used,
    # configure the ingress to point to the Vault active service.
    activeService: true
    hosts:
      - host: vault.isandeshsol.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vault-tls
        hosts:
          - vault.isandeshsol.com

# Vault UI
ui:
  # True if you want to create a Service entry for the Vault UI.
  #
  # serviceType can be used to control the type of service created. For
  # example, setting this to "LoadBalancer" will create an external load
  # balancer (for supported K8S installations) to access the UI.
  enabled: true
  publishNotReadyAddresses: true
  serviceType: "ClusterIP"
  externalPort: 8200
  targetPort: 8200
