server:
  dev:
    enabled: true

  service:
    enabled: true

  # ingress:
  #   enabled: true
  #   ingressClassName: traefik
  #   annotations:
  #     traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #     traefik.ingress.kubernetes.io/router.tls: "true"
  #     cert-manager.io/cluster-issuer: letsencrypt-stg
  #     cert-manager.io/common-name: vault.isandeshsol.com
  #     # Optional: External DNS
  #     # external-dns.alpha.kubernetes.io/hostname: vault.example.com
  #   hosts:
  #     - host: vault.isandeshsol.com
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #   tls:
  #     - secretName: vault-tls
  #       hosts:
  #         - vault.isandeshsol.com

# Enable Vault Agent Injector Webhook
injector:
  enabled: false

# Clean up extra features
csi:
  enabled: false

# Expose the Vault UI (optional)
ui:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.1.85 # If using MetalLB
