server:
  dev:
    enabled: true

  service:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt-stg
      cert-manager.io/common-name: vault.isandeshsol.com
    hosts:
      - host: vault.isandeshsol.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vault-tls
        hosts:
          - vault.isandeshsol.com

# Expose the Vault UI (optional)
ui:
  enabled: true
  serviceType: "ClusterIP"
