apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki
  namespace: loki-stack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
  hostnames:
    - loki.isandeshsol.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: loki-gateway
          port: 80
