apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  # annotations:
  #   kubernetes.io/ingress.class: traefik-external
  #   cert-manager.io/cluster-issuer: letsencrypt-stg
  #   acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.longhorn.isandeshsol.com`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 8000
    - match: Host(`longhorn.isandeshsol.com`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 8000
  tls:
    secretName: longhorn-ingress-stg
    certResolver: letsencrypt-stg # Reference the cert-manager resolver
    domains:
      - main: longhorn.isandeshsol.com
