apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.longhorn.isandeshsol.com`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 8000
    - match: Host(`longhorn.isandeshsol.com`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 8000
  tls:
    secretName: longhorn-ingress-tls
