apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.88 # Must be within MetalLB IP pool
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: longhorn-ui
