# values.yaml - Minimal config for RPi
# Disable ALL components except LocalPV Hostpath

# Disable legacy components
ndm:
  enabled: false
ndmOperator:
  enabled: false
cstor:
  enabled: false
jiva:
  enabled: false
zfs-localpv:
  enabled: false

# Disable v4.x components
engines:
  replicated:
    mayastor: 
      enabled: false  # Disable Mayastor
  local:
    hostpath:
      enabled: true   # Keep ONLY Hostpath
    lvm:
      enabled: false  # Disable LVM
    zfs:
      enabled: false  # Disable ZFS

# Disable monitoring stack
observability:
  enabled: false  # Disable Loki/Promtail

# Disable etcd and NATS
etcd:
  enabled: false
nats:
  enabled: false

# LocalPV Hostpath config
localprovisioner:
  enabled: true
  basePath: /var/openebs/local

# ✅ Enable NFS Provisioner for RWX
nfsProvisioner:
  enabled: true
  replicaCount: 3  # You can increase for HA NFS
  storageClass:
    create: true
    name: openebs-nfs-rwx
    defaultClass: false
  backendStorageClass: openebs-hostpath  # This must match your LocalPV hostpath SC
  nfsServer:
    image:
      repository: quay.io/openebs/nfs-server-alpine
      tag: "v3.3.0"