apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudnative-pg

resources:
  - namespace.yaml

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg
    version: 0.21.3 # update to latest if needed
    namespace: cloudnative-pg
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-6"
