service:
  type: ClusterIP
  port: 80
  targetPort: 80
  # targetPort: 4181 To be used with a proxy extraContainer
  portName: http

existingSecret: "pgadmin4-secret"

secretKeys:
  pgadminPasswordKey: password

ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    cert-manager.io/common-name: pgadmin.isandeshsol.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels: {}
  hosts:
    - host: pgadmin.isandeshsol.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - pgadmin.isandeshsol.com
      secretName: pgadmin-tls