service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  # targetPort: 4181 To be used with a proxy extraContainer
  portName: http

existingSecret: "pgadmin4-secret"

secretKeys:
  pgadminPasswordKey: password
