apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    kubernetes.io/ingress.class: traefik-external
spec:
  ingressClassName: traefik-external
  rules:
    - host: argocd.isandeshsol.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
  tls:
    - hosts:
        - argocd.isandeshsol.com
      secretName: argocd-tls
