apiVersion: traefik.io/v1alpha1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik-external
    cert-manager.io/cluster-issuer: letsencrypt-stg
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
    - host: argocd.isandeshsol.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
  tls:
    - hosts:
        - argocd.isandeshsol.com
      secretName: argocd-ingress-stg
