apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik-external
    cert-manager.io/cluster-issuer: letsencrypt-stg
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.argocd.isandeshsol.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.isandeshsol.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: argocd-ingress-stg
