apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`www.argocd.isandeshsol.com`)
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.isandeshsol.com`)
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: argocd-ingress-stg # Traefik stores the certificate in this secret
    certResolver: letsencrypt-stg # Reference the cert-manager resolver
    domains:
      - main: argocd.isandeshsol.com
