apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.argocd.isandeshsol.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.isandeshsol.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    - hosts:
        - argocd.isandeshsol.com
      secretName: argocd-ingress-stg
