tunnel: k3s-cluster-prd
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
loglevel: debug
transport-loglevel: debug

ingress:
  - hostname: hello.isandeshsol.com
    service: http://traefik.kube-system.svc.cluster.local:80
    originRequest:
      logHeaders: true

  - hostname: "*.isandeshsol.com"
    service: https://traefik.kube-system.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      originServerName: "*.isandeshsol.com"
      logHeaders: true

  - hostname: isandeshsol.com
    service: https://traefik.kube-system.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      originServerName: isandeshsol.com
      logHeaders: true

  - service: http_status:404
