tunnel: k3s-cluster-prd
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: "*.isandeshsol.com"
    service: http://traefik.kube-system.svc.cluster.local:80
  - service: http_status:404
