tunnel: k3s-cluster-prd
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: argocd.isandeshsol.com
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      httpHostHeader: argocd.isandeshsol.com
      logHeaders: true
      connectTimeout: 30s

  - hostname: homepage.isandeshsol.com
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      httpHostHeader: homepage.isandeshsol.com
      logHeaders: true
      connectTimeout: 30s

  - hostname: portfolio.isandeshsol.com
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      httpHostHeader: portfolio.isandeshsol.com
      logHeaders: true
      connectTimeout: 30s

  - hostname: grafana.isandeshsol.com
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      httpHostHeader: grafana.isandeshsol.com
      logHeaders: true
      connectTimeout: 30s

  - service: http_status:404
