tunnel: k3s-cluster-prd
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: argocd.isandeshsol.com
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      logHeaders: true

  - hostname: homepage.isandeshsol.com
    service: https://traefik.traefik.svc.cluster.local:80
    originRequest:
      noTLSVerify: true
      logHeaders: true

  - service: http_status:404
