apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - namespace.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cloudflared-config
    files:
      - config.yaml
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
# NOTE: Secret (credentials) should be created manually via kubectl:
# kubectl -n cloudflared create secret generic tunnel-credentials --from-file=credentials.json
