apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml

helmCharts:
  - name: coder
    releaseName: coder
    repo: https://helm.coder.com/v2
    namespace: coder
    version: 2.26.0
    valuesFile: values.yaml
