apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-database
  namespace: coder
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    storageClass: longhorn
    size: 10Gi
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-db-secret
